defaults:
  - CLIPVisionModelPool@: _template
  - /model/clip-vit@models:
      - clip-vit-large-patch14
      - clip-vit-large-patch14_stanford-cars
      - clip-vit-large-patch14_eurosat
      - clip-vit-large-patch14_resisc45
      - clip-vit-large-patch14_gtsrb
  - /dataset/image_classification/train@train_datasets:
      - stanford-cars
      - eurosat
      - resisc45
      - gtsrb
  - /dataset/image_classification/test@test_datasets:
      - stanford-cars
      - eurosat
      - resisc45
      - gtsrb
