defaults:
  - CLIPVisionModelPool@: _template
  - /model/clip-vit@models:
      - clip-vit-base-patch16
      - clip-vit-base-patch16_stanford-cars
      - clip-vit-base-patch16_resisc45
      - clip-vit-base-patch16_svhn
      - clip-vit-base-patch16_gtsrb
      - clip-vit-base-patch16_mnist
      - clip-vit-base-patch16_dtd
  - /dataset/image_classification/train@train_datasets:
      - stanford-cars
      - resisc45
      - svhn
      - gtsrb
      - mnist
      - dtd
  - /dataset/image_classification/test@test_datasets:
      - stanford-cars
      - resisc45
      - svhn
      - gtsrb
      - mnist
      - dtd