defaults:
  - CLIPVisionModelPool@: _template
  - /model/clip-vit@models:
      - clip-vit-base-patch32
      - clip-vit-base-patch32_resisc45
      - clip-vit-base-patch32_eurosat
      - clip-vit-base-patch32_svhn
      - clip-vit-base-patch32_gtsrb
      - clip-vit-base-patch32_mnist
      - clip-vit-base-patch32_dtd
  - /dataset/image_classification/train@train_datasets:
      - resisc45
      - eurosat
      - svhn
      - gtsrb
      - mnist
      - dtd
  - /dataset/image_classification/test@test_datasets:
      - resisc45
      - eurosat
      - svhn
      - gtsrb
      - mnist
      - dtd