defaults:
  - CLIPVisionModelPool@: _template
  - /model/clip-vit@models:
      - clip-vit-base-patch16
      - clip-vit-base-patch16_sun397
      - clip-vit-base-patch16_resisc45
      - clip-vit-base-patch16_eurosat
      - clip-vit-base-patch16_gtsrb
      - clip-vit-base-patch16_mnist
      - clip-vit-base-patch16_dtd
  - /dataset/image_classification/train@train_datasets:
      - sun397
      - resisc45
      - eurosat
      - gtsrb
      - mnist
      - dtd
  - /dataset/image_classification/test@test_datasets:
      - sun397
      - resisc45
      - eurosat
      - gtsrb
      - mnist
      - dtd