defaults:
  - CLIPVisionModelPool@: _template
  - /model/clip-vit@models:
      - clip-vit-large-patch14
      - clip-vit-large-patch14_stanford-cars
      - clip-vit-large-patch14_eurosat
      - clip-vit-large-patch14_resisc45
      - clip-vit-large-patch14_gtsrb
  - /dataset/image_classification/train@train_datasets:
      - stanford-cars
      - eurosat
      - resisc45
      - gtsrb
# `corrption` can be one of:
# contrast, gaussian_noise, impulse_noise, jpeg_compression, motion_blur, pixelate, spatter
corruption: ${corruption}
# The following datasets are used for test-time adaptation
test_datasets:
  stanford-cars:
    _target_: datasets.load_dataset
    path: tanganke/stanford_cars
    split: ${...corruption}
  eurosat:
    _target_: datasets.load_dataset
    path: tanganke/eurosat
    split: ${...corruption}
  resisc45:
    _target_: datasets.load_dataset
    path: tanganke/resisc45
    split: ${...corruption}
  gtsrb:
    _target_: datasets.load_dataset
    path: tanganke/gtsrb
    split: ${...corruption}
