defaults:
  - CLIPVisionModelPool@: _template
  - /model/clip-vit@models:
      - clip-vit-base-patch16
      - clip-vit-base-patch16_sun397
      - clip-vit-base-patch16_stanford-cars
      - clip-vit-base-patch16_eurosat
      - clip-vit-base-patch16_svhn
      - clip-vit-base-patch16_gtsrb
      - clip-vit-base-patch16_dtd
  - /dataset/image_classification/train@train_datasets:
      - sun397
      - stanford-cars
      - eurosat
      - svhn
      - gtsrb
      - dtd
  - /dataset/image_classification/test@test_datasets:
      - sun397
      - stanford-cars
      - eurosat
      - svhn
      - gtsrb
      - dtd