defaults:
  - CLIPVisionModelPool@: _template
  - /model/clip-vit@models:
      - clip-vit-base-patch16
      - clip-vit-base-patch16_stanford-cars
      - clip-vit-base-patch16_eurosat
      - clip-vit-base-patch16_resisc45
      - clip-vit-base-patch16_gtsrb
  - /dataset/image_classification/train@train_datasets:
      - stanford-cars
      - eurosat
      - resisc45
      - gtsrb
  - /dataset/image_classification/test@test_datasets:
      - stanford-cars
      - eurosat
      - resisc45
      - gtsrb
