defaults:
  - CLIPVisionModelPool@: _template
  - /model/clip-vit@models:
      - clip-vit-large-patch14
      - clip-vit-large-patch14_stanford-cars
      - clip-vit-large-patch14_resisc45
      - clip-vit-large-patch14_eurosat
      - clip-vit-large-patch14_svhn
      - clip-vit-large-patch14_gtsrb
      - clip-vit-large-patch14_dtd
  - /dataset/image_classification/train@train_datasets:
      - stanford-cars
      - resisc45
      - eurosat
      - svhn
      - gtsrb
      - dtd
  - /dataset/image_classification/test@test_datasets:
      - stanford-cars
      - resisc45
      - eurosat
      - svhn
      - gtsrb
      - dtd